site_name: TEKOHARENDA - Catálogo Nacional de Datos Espaciales del Paraguay
site_description: Catálogo Nacional de Datos Espaciales del Paraguay
site_url: https://carlosgl91.github.io/tekoharenda 

theme:
  name: material
  palette:
    primary: teal
  logo: assets/logo_tekoharenda_png.png 
  features:
    #- navigation.tabs
    #- navigation.sections
    #- navigation.tabs.sticky
    #- navigation.footer
    - search.suggest
   # - toc.integrate         # Integra los subtítulos en el menú izquierdo
    - navigation.expand     # Hace que las categorías sean desplegables
    - navigation.sections   # Hace que los bloques del menú se vean más como secciones ordenadas
extra_css:
  - stylesheets/extra.css
nav:
  - Inicio: index.md
  - Catálogo de Datos:
    - Clima:
      - 'Promedio anual de precipitación acumulada periodo 01-01-1994 a 01-01-2024': datasets/climate/annual_prec_1994_2024_chirps_pentad.md
      - 'Temperatura anual promedio en el periodo 1991-2019': datasets/climate/annual_temp_19912019_era5.md
      - 'Datos de WorldClimb 1970-2000': datasets/climate/worldclimb_19702000.md
    - Ecología:
      - 'Formaciones forestales mayores o iguales a 1ha - Año 2023': datasets/ecology/formaciones_forestales_mayores_o_iguales_a_1ha__ao.md
      - 'Formaciones forestales más de 100 ha': datasets/ecology/formaciones_forestales_ms_de_100_ha.md
      - 'Áreas urbanas de Paraguay a partir de INE 2022': datasets/ecology/urban_areas_py_ine_2022.md
      - 'Areas urbananas de Paraguay a partir de INE 2022 Y OSM 2025': datasets/ecology/urban_areas_ine_&_osm_2022.md
      - 'Distancia al borde dentro de formaciones boscosas de al meno 1 ha': datasets/ecology/dist_to_border_within_forest_1ha.md
      - 'Distancia a ecosistemas acuáticos lóticos': datasets/ecology/dist_to_lotic_ecosystems.md
      - 'Distancia a la red vial': datasets/ecology/dist_to_road_network.md
      - 'Distancia a áreas urbanas': datasets/ecology/dist_to_urban_areas_ine_2022.md
      - 'Distancia a áreas urbanas, industriales y comerciales': datasets/ecology/dist_to_urban_industrial_and_comercial_areas.md
      - 'Distancia a formaciones forestales de más de 100 hectáreas': datasets/ecology/dist_to_forest_border_100_ha.md
    - Estatus de uso:
      - 'Áreas certificadas bajo el régimen de servicios ambientales': datasets/estatus_de_proteccion/areas_certificadas_csa.md
      - 'Áreas silvestres protegidas de Paraguay actualizado a agosto de 2022': datasets/estatus_de_proteccion/areas_silvestres_protegidas.md
      - 'Comunidades indígenas FAPI 2024': datasets/estatus_de_proteccion/comunidades_indgenas_fapi_2024.md
      - 'Comunidades indígenas INDI 2024': datasets/estatus_de_proteccion/comunidades_indgenas_indi_2024.md    
    - Topografía:
      - 'Elevation TanDEM-X EDEM': datasets/topography/elevation_tandemx_edem.md
      - 'El SRTM Digital Elevation Data Version 4 (SRTM v4)': datasets/topography/srtm_dem_version_v4.md
    
    - Uso y cobertura del suelo:
      - 'MapBiomas colección 5 1985-2023': datasets/landcover_landuse/mapbiomas_col_5_19852023.md
      
    - Suelos:    
      - 'Taxonomía del suelo en la Región Oriental': datasets/soils/soil_tax_east_reg_soil_taxonomy.md
      - 'Taxonomía del suelo en la Región Occidental': datasets/soils/soil_tax_west_reg_fao_class.md
    - Fuego:
      - 'MapBiomas Fuego colección 1 (Anual)': datasets/fire/mapbiomas_fire_col1_annual.md
      - 'MapBiomas Fuego colección 1 (Mensual)': datasets/fire/mapbiomas_fire_col1_monthly.md

  - Citación: citation.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/carlos-gim%C3%A9nez-3b3267169/
      name: Carlos Giménez
copyright: Copyright &copy; 2026 Carlos Giménez
